server.port=${PORT:8080}
server.servlet.context-path=/api/v1

spring.application.name=kidclothes
spring.data.mongodb.uri=${MONGODB_URI}

jwt.signerKey=${JWT_SIGNER_KEY}
jwt.valid-duration=168
jwt.refreshable-duration=240
