server.port=${PORT:8080}
server.servlet.context-path=/api/v1

spring.application.name=kidclothes
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://springuser:springuser@cluster0.9h6ba9h.mongodb.net/kidclothes?retryWrites=true&w=majority&tls=true}

jwt.signerKey=${JWT_SIGNER_KEY:eniiM][etiU(Vc@gFrBsIV3ovELA6l2h2PG8]3{bNoJ2ty(LmZ(SaBXbcn=bMl4G}
jwt.valid-duration=168
jwt.refreshable-duration=240
